apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: nginx
        image: gcr.io/gcp-devops-model/gk-image:v1.0
        ports:
        - containerPort: 80
